// 2. Company Profile Schema (detailed company info)
export const companyProfileSchema = {
  name: 'companyProfile',
  title: 'Company Profile',
  type: 'document',
  fields: [
    { name: 'companyName', title: 'Company Name', type: 'string' },
    { name: 'industrySector', title: 'Industry Sector', type: 'string' },
    { name: 'foundedYear', title: 'Founded Year', type: 'number' },
    { name: 'headquartersLocation', title: 'Headquarters Location', type: 'string' },
    { name: 'numberOfEmployees', title: 'Number of Employees', type: 'number' },
    { name: 'website', title: 'Website', type: 'url' },
    { name: 'isPublic', title: 'Is Public', type: 'boolean' },
    { name: 'latestValuation', title: 'Latest Valuation', type: 'string' },
    { name: 'investmentStatus', title: 'Investment Status', type: 'string' },
    { 
      name: 'management', 
      title: 'Management Team', 
      type: 'array', 
      of: [{ type: 'string' }] 
    },
    { 
      name: 'valuationRecords', 
      title: 'Valuation Records', 
      type: 'array', 
      of: [
        {
          type: 'object',
          fields: [
            { name: 'date', title: 'Date', type: 'string' },
            { name: 'value', title: 'Value', type: 'number' }
          ]
        }
      ]
    },
    {
      name: 'faqs',
      title: 'FAQs',
      type: 'array',
      of: [{
        type: 'object',
        fields: [
          { name: 'question', title: 'Question', type: 'string' },
          { name: 'answer', title: 'Answer', type: 'text' },
          { name: 'isAutoGenerated', title: 'Auto-Generated', type: 'boolean' }
        ]
      }]
    }
  ]
};
