name: Deploy

on:
  push:
    branches:
      - staging

jobs:
  deploy-production:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.6.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STG }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STG }}
          aws-region: eu-central-1

      - name: Checkout
        uses: actions/checkout@v2.5.0

      - name: Setup Node.js
        uses: actions/setup-node@v3.2.0
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install --force

      - name: Build
        run: npm run build

      - name: Deploy to S3 (Staging)
        run: aws s3 sync ./dist s3://pe-projects-platforms/sanity/staging/

      - name: Invalidate CloudFront Cache (Staging)
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID_STAGING }} --paths "/*"
